### ISSUE TITLE
Update to .NET 6

### ISSUE THREAD

**Issue by orosbogdan** [CAMongrel/D3D12SampleRaytracerSharp#1]
Would be much appreciate if the sample projects would be updated to .net 6

**Comment by CAMongrel** [comment]
Project updated to .NET 6 in https://github.com/CAMongrel/D3D12SampleRaytracerSharp/commit/e25968164080eff8615c717a7994ae9a721d410d and subsequently updated to .NET 7 in https://github.com/CAMongrel/D3D12SampleRaytracerSharp/commit/5a39fdb57a2fb3ee5968b4debf585921aff8d2a5
